[package]
name = "dex-builder"
version = "0.3.0-beta.2"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [features]
# default = []
# generate = []

[dependencies]

### Pokemon specifications

firecore-pokedex = { git = "https://github.com/DoNotDoughnut/firecore-pokedex" }
#firecore-pokedex-lib = { path = "../../firecore/firecore-pokedex-lib" }

### Serialization

serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
toml = "0.5"