[package]
name = "firecore-pokedex-builder"
version = "0.5.0-2021-08-22"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>"]
edition = "2018"

[dependencies]
firecore-pokedex = { git = "https://github.com/DoNotDoughnut/firecore-pokedex" }
ron = "0.6"