[package]
name = "firecore-pokedex-builder"
version = "0.0.6"
authors = ["Rhys H <donotdoughnut99@gmail.com>"]
edition = "2018"

[dependencies]
firecore-pokedex = { git = "https://github.com/fiirecore/pokedex", rev = "a99a343" }
ron = "0.6"